# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 832d21453c0171338c4a2d0a5071c60831dd916ba1a1c211fd7cbb8d761fba6e7733184cebf8a659a1954c6d245eddf3b5863aa7a606e3d3ad9abf01ee1b80ae

test:
  secret_key_base: 798adda1662cd1f55f78eb549e71e2c6175c2957fbd688c21d43e868b594d64aefd8f5b34e84205150ffaa5446714e29115afb4f0b4b5a690ad78e8910c76662

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
